package com.tstasks.sanchellios.navicostores;

/**
 * Created by alex on 17.08.16.
 */
public class Transliterator {
    public static String getRussianString(String translit){
        String updatedString = translit.replaceAll("Ts", "Ц")
                .replaceAll("ts", "ц")
                .replaceAll("Ya", "Я")
                .replaceAll("ya", "я")
                .replaceAll("Ta", "Тя")
                .replaceAll("ta", "тя")
                .replaceAll("Ny", "Ный")
                .replaceAll("ny", "ный")
                .replaceAll("Sound", "Саунд")
                .replaceAll("sound", "саунд");
        return transliterate(updatedString);
    }

    private static String transliterate(String string){
        String updatedString = string.replaceAll("A", "А")
                .replaceAll("a", "а")
                .replaceAll("B", "Б")
                .replaceAll("b", "б")
                .replaceAll("V", "В")
                .replaceAll("v", "в")
                .replaceAll("G", "Г")
                .replaceAll("g", "г")
                .replaceAll("D", "Д")
                .replaceAll("d", "д")
                .replaceAll("E", "Е")
                .replaceAll("e", "е")
                .replaceAll("Jo", "Ё")
                .replaceAll("jo", "ё")
                .replaceAll("Zh", "Ж")
                .replaceAll("zh", "ж")
                .replaceAll("Z", "З")
                .replaceAll("z", "з")
                .replaceAll("I", "И")
                .replaceAll("i", "и")
                .replaceAll("J", "Й")
                .replaceAll("j", "й")
                .replaceAll("K", "К")
                .replaceAll("k", "к")
                .replaceAll("L", "Л")
                .replaceAll("l", "л")
                .replaceAll("M", "М")
                .replaceAll("m", "м")
                .replaceAll("N", "Н")
                .replaceAll("n", "н")
                .replaceAll("O", "О")
                .replaceAll("o", "о")
                .replaceAll("P", "П")
                .replaceAll("p", "п")
                .replaceAll("R", "Р")
                .replaceAll("r", "р")
                .replaceAll("S", "С")
                .replaceAll("s", "с")
                .replaceAll("T", "Т")
                .replaceAll("t", "т")
                .replaceAll("U", "У")
                .replaceAll("u", "у")
                .replaceAll("F", "Ф")
                .replaceAll("f", "ф")
                .replaceAll("H", "Х")
                .replaceAll("h", "х")
                .replaceAll("C", "Ц")
                .replaceAll("c", "ц")
                .replaceAll("Ch", "Ч")
                .replaceAll("ch", "ч")
                .replaceAll("Sh", "Ш")
                .replaceAll("sh", "ш")
                .replaceAll("Shh", "Щ")
                .replaceAll("shh", "щ")
                .replaceAll("##", "Ъ")
                .replaceAll("#", "ъ")
                .replaceAll("Y", "Ы")
                .replaceAll("y", "ы")
                .replaceAll("\''", "Ь")
                .replaceAll("\'", "ь")
                .replaceAll("Je", "Э")
                .replaceAll("je", "э")
                .replaceAll("Ju", "Ю")
                .replaceAll("ju", "ю")
                .replaceAll("Yu", "Ю")
                .replaceAll("yu", "ю")
                .replaceAll("Ja", "Я")
                .replaceAll("ja", "я");
        return updatedString;
    }
}
